/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {
    val a = 0
    val b = 1
    val c = 1
    if (a === 0) {
        println("El coeficiente cuadratico debe ser diferente de cero")
        return
    }
    println("La función es: ${a}x² + ${b}x + $c")
}
